# Generated by Django 3.0.7 on 2020-06-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, default='hello')),
                ('file', models.FileField(upload_to='AudioQuestions/music')),
                ('image', models.ImageField(blank=True, upload_to='AudioQuestions/images')),
                ('answer', models.CharField(max_length=200)),
                ('intans', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, default='hello')),
                ('image', models.ImageField(blank=True, upload_to='StaticQuestions/images')),
                ('answer', models.CharField(max_length=200)),
                ('intans', models.IntegerField()),
            ],
        ),
    ]
