# Generated by Django 3.0.7 on 2020-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioquestions',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='audioquestions',
            name='intans',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='audioquestions',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='intans',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='staticquestions',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
