# Generated by Django 3.0.7 on 2020-06-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200618_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticquestions',
            name='intans',
        ),
    ]
