# Generated by Django 3.0.7 on 2020-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_audioquestions_intans'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioquestions',
            name='hint',
            field=models.TextField(blank=True, default='hint'),
        ),
        migrations.AddField(
            model_name='staticquestions',
            name='hint',
            field=models.TextField(blank=True, default='hint'),
        ),
    ]
