# Generated by Django 3.0.7 on 2020-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200622_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticquestions',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/StaticQuestions/images'),
        ),
    ]
