# Generated by Django 3.0.7 on 2020-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200624_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticquestions',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
