# Generated by Django 3.0.7 on 2020-06-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_staticquestions_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticquestions',
            name='image',
            field=models.ImageField(blank=True, upload_to='StaticQuestions/images'),
        ),
    ]
