# Generated by Django 3.0.7 on 2020-07-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200702_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticQuestions',
            new_name='Stage1',
        ),
        migrations.DeleteModel(
            name='AudioQuestions',
        ),
    ]
