# Generated by Django 3.0.7 on 2020-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200702_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage1',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
