# Generated by Django 3.0.7 on 2020-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200702_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, default='hello')),
                ('image', models.ImageField(blank=True, upload_to='StaticQuestions/images')),
                ('image_url', models.URLField(blank=True)),
                ('hint', models.TextField(blank=True, default='hint')),
                ('answer_x', models.CharField(blank=True, max_length=200)),
                ('answer_y', models.CharField(blank=True, max_length=200)),
                ('answer_z', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Stage1',
        ),
    ]
