# Generated by Django 3.0.7 on 2020-07-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200702_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_1',
            name='answer_y',
        ),
        migrations.RemoveField(
            model_name='stage_1',
            name='answer_z',
        ),
        migrations.AlterField(
            model_name='stage_1',
            name='answer_x',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
