# Generated by Django 3.0.7 on 2020-07-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200702_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage_1',
            old_name='answer_x',
            new_name='answer',
        ),
    ]
