# Generated by Django 3.0.7 on 2020-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200702_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage_1',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
