# Generated by Django 3.0.7 on 2020-07-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_stage_1_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_1',
            name='taken',
        ),
    ]
