# Generated by Django 3.0.7 on 2020-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200624_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(default='none', max_length=400),
        ),
        migrations.AddField(
            model_name='player',
            name='contact',
            field=models.CharField(blank=True, default='nan', max_length=15),
        ),
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
