# Generated by Django 3.0.7 on 2020-06-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200628_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact',
            field=models.IntegerField(blank=True, default=1, max_length=15),
        ),
    ]
