# Generated by Django 3.0.7 on 2020-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200628_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
