# Generated by Django 3.0.7 on 2020-06-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200628_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(default='none', max_length=400),
        ),
        migrations.AddField(
            model_name='player',
            name='contact',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.DeleteModel(
            name='PlayerDetails',
        ),
    ]
