# Generated by Django 3.0.7 on 2020-06-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200628_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdetails',
            name='name',
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='college',
            field=models.ForeignKey(default='none', max_length=400, on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
        ),
    ]
