# Generated by Django 3.0.7 on 2020-06-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200628_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='name_user',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='college',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
