# Generated by Django 3.0.7 on 2020-06-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_playerdetails_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
            preserve_default=False,
        ),
    ]
