# Generated by Django 3.0.7 on 2020-06-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200628_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
        ),
    ]
