# Generated by Django 3.0.7 on 2020-07-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200701_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Player'),
        ),
    ]
