# Generated by Django 3.0.7 on 2020-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200701_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='contact',
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
