# Generated by Django 3.0.7 on 2020-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200702_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='full_name',
            field=models.CharField(default='your name', max_length=400),
        ),
    ]
