# Generated by Django 3.0.7 on 2020-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_playerdetails_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='question_level',
            field=models.IntegerField(default=1),
        ),
    ]
